spring:
  config:
    import: optional:file:.env[.properties]
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      database: grade
      port: 27017
      host: localhost
  flyway:
    url: mongodb://localhost:27017
    locations: classpath:db/migration

server:
  port: 8082

topics: grade-topic
