-- INSERT для таблицы `subject`
INSERT INTO subject (subject_name) VALUES ('Mathematics'), ('Physics'), ('Biology'), ('Chemistry'), ('History'), ('Literature'),
                                          ('English'), ('Geography'), ('Computer Science'), ('Art'), ('Music'), ('Physical Education'),
                                          ('Economics'), ('Psychology'), ('Philosophy'), ('Sociology'), ('Political Science'),
                                          ('Foreign Language'), ('Business'), ('Statistics'), ('Anthropology'), ('Environmental Science'),
                                          ('Architecture'), ('Engineering'), ('Medicine'), ('Law'), ('Journalism'), ('Film Studies'),
                                          ('Culinary Arts'), ('Marketing'), ('Finance');

-- INSERT для таблицы teacher
INSERT INTO teacher (firstname, lastname, patronymic, age, item_name) VALUES
                                                                          ('John', 'Doe', 'Smith', 40, 'Mathematics'),
                                                                          ('Alice', 'Johnson', 'Brown', 35, 'Physics'),
                                                                          ('Michael', 'Smith', 'Wilson', 32, 'Chemistry'),
                                                                          ('Emma', 'Davis', 'Jones', 28, 'Biology'),
                                                                          ('Daniel', 'Wilson', 'Lee', 41, 'English'),
                                                                          ('Sophia', 'Thomas', 'Taylor', 37, 'History'),
                                                                          ('Liam', 'Anderson', 'White', 29, 'Geography'),
                                                                          ('Olivia', 'Brown', 'King', 33, 'Computer Science'),
                                                                          ('Noah', 'Clark', 'Harris', 35, 'Literature'),
                                                                          ('Ava', 'Martin', 'Thomas', 42, 'Art'),
                                                                          ('James', 'Young', 'Hill', 31, 'Music'),
                                                                          ('Isabella', 'Garcia', 'Scott', 38, 'Physical Education'),
                                                                          ('Benjamin', 'Lewis', 'Walker', 34, 'Economics'),
                                                                          ('Mia', 'Hall', 'Collins', 39, 'Psychology'),
                                                                          ('William', 'Allen', 'Green', 40, 'Philosophy'),
                                                                          ('Charlotte', 'Adams', 'Roberts', 36, 'Sociology'),
                                                                          ('Henry', 'Parker', 'Hernandez', 30, 'Foreign Language'),
                                                                          ('Ella', 'Turner', 'Morris', 27, 'Business'),
                                                                          ('Alexander', 'Cook', 'Davis', 31, 'Statistics'),
                                                                          ('Harper', 'Baker', 'Lopez', 29, 'Environmental Science'),
                                                                          ('Sofia', 'Gonzalez', 'Kelly', 33, 'Engineering'),
                                                                          ('Jackson', 'Ward', 'Ross', 27, 'Medicine'),
                                                                          ('Amelia', 'Cruz', 'Price', 35, 'Law'),
                                                                          ('Owen', 'Mitchell', 'Young', 32, 'Journalism'),
                                                                          ('Emily', 'Perez', 'Simmons', 30, 'Film Studies');