server:
  port: 8080

spring:
  config:
    import: optional:file.env[.properties]
  datasource:
    password: 2121
    username: postgres
    url: jdbc:postgresql://localhost:5432/schedule
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true


grpc:
  client:
    GLOBAL:
      address: localhost:8980
      negotiation-type: plaintext

push:
  batch-size: ${BATCH_SIZE}

