name: Docker Image CI


on:
  push:
    branches: ["main"]  # когда у нас в main что то встаялеся мы будем выполнять этот workflow (событие)


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push to Docker Hub
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/diary-service-consumer
          tags: 0.0.$GITHUB_RUN-NUMBER, latest
          dockerfile: Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}