spring:
  config:
    import: optional:file.env[.properties]
  kafka:
    bootstrap-servers: localhost:9092
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
  datasource:
    username: postgres
    password: 2121
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres

server:
  port: 8081


push:
  batch-size: ${BATCH_SIZE}

grpc:
  server:
    port: 8980
